#!/bin/sh

set -e
set -x

#DEBHELPER#

case "$1" in
    configure)
	ucf --three-way /usr/share/nfs-kernel-server/conffiles/etc.exports /etc/exports
	ucf --three-way /usr/share/nfs-kernel-server/conffiles/nfs-kernel-server.default /etc/default/nfs-kernel-server

	# Create state files if missing, using backups created during
	# preinst if present
	for f in /var/lib/nfs/etab  \
		 /var/lib/nfs/rmtab; do
	    if [ -f "$f.bak" ]; then
		mv -n "$f.bak" "$f" || rm -f "$f.bak"
	    else
		[ -e "$f" ] || touch "$f"
	    fi
	done

	update-rc.d nfs-kernel-server defaults 20 80 >/dev/null

	# Remove leftover /fsid.sock file on upgrade (Cf. #1041147)
	if dpkg --compare-versions "$2" lt 1:2.6.3-2~; then
		if [ -S /fsid.sock ]; then
			rm -f /fsid.sock
		fi
	fi
    ;;
esac
